version: '3.9'
services:
  app:
    container_name: inubot-discord
    image: inubot-discord:latest
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../data
        target: /data
    env_file:
      - ../.env
    restart: always
