version: '3.9'
services:
  app:
    container_name: nishinokanabot-discord
    image: ghcr.io/iamtakagi/nishinokanabot-discord:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: ../src
        target: /src
      - type: bind
        source: ../data
        target: /data
    env_file:
      - ../.env
    restart: always
